name = "gbase32_clockwork"
version = "2.0.1"
gleam = ">= 0.32.0"

description = "base32 clockwork in gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "dropwhile", repo = "gbase32_clockwork" }

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
